version: "2"

linters:
  default: none
  enable:
    # default rules
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # other rules
    - asasalint
    - asciicheck
    - bidichk
    - depguard
    - durationcheck
    - forbidigo
    - gocritic
    - gocheckcompilerdirectives
    - gosec
    - makezero
    - nilerr
    - nolintlint
    - reassign
    - sqlclosecheck
    - unconvert
  settings:
    nolintlint:
      require-explanation: true
      require-specific: true

    staticcheck:
      checks:
        - "all"
        - "-ST*"    # stylecheck: not previously enabled (merged into staticcheck in v2)
        - "-QF*"    # quickfix suggestions: not previously enabled (merged into staticcheck in v2)

    forbidigo:
      forbid:
        - pattern: "^(fmt\\.Print(|f|ln)|print|println)$"
        - pattern: "^(fmt\\.Fprint(|f|ln)|print|println)$"
        - pattern: '^zap\.Error$'
        - pattern: '^grpc\.(Header|Trailer)$' # easy to misuse and create a data race

    gocritic:
      disabled-checks:
        - ifElseChain       # style
        - singleCaseSwitch  # style & it's actually not a bad idea to use single case switch in some cases
        - assignOp          # style
        - commentFormatting # style

    depguard:
      rules:
        # Name of a rule.
        main:
          # Packages that are not allowed where the value is a suggestion.
          deny:
            - pkg: "go.uber.org/zap"
              desc: do not use Uber zap directly, use the fplog package instead
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
  exclusions:
    presets:
      - std-error-handling    # errcheck: unchecked Close/Remove/print calls
      - common-false-positives # gosec: G103, G204, G304 false positives
      - legacy                 # gosec: G104, G301, G302, G307
    rules:
      # gosec rules not covered by presets - pre-existing findings
      - linters: [gosec]
        text: "G101:"
      - linters: [gosec]
        text: "G602:"
      - linters: [gosec]
        text: "G706:"
    paths:
      - "tests/acceptance"

run:
  timeout: 5m
