before:
  hooks:
    - go mod tidy
builds:
  - id: "powerpipe"
    # Custom ldflags.
    #
    # Default: '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser'
    # Templates: allowed
    ldflags:
      # Go Releaser analyzes your Git repository and identifies the most recent Git tag (typically the highest version number) as the version for your release.
      # This is how it determinse the value of {{.Version}}.
      - -s -w -X main.version={{.Version}} -X version.buildTime={{.Date}} -X version.commit={{.Commit}} -X version.builtBy=goreleaser
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "powerpipe"

archives:
  - format: tar.gz
    id: homebrew
    name_template: "{{ .ProjectName }}.{{ .Os }}.{{ .Arch }}"

nfpms:
  - id: "powerpipe"
    builds: ["powerpipe"]
    formats:
      - deb
      - rpm
    vendor: "powerpipe.io"
    homepage: "https://powerpipe.io/"
    maintainer: "Turbot Support <help@turbot.com>"
    description: "Use SQL to instantly query your cloud services (AWS, Azure, GCP and more). Open source CLI. No DB required."
    file_name_template: "{{ .ProjectName }}.{{ .Os }}.{{ .Arch }}"
    rpm:
      summary: "Use SQL to instantly query your cloud services (AWS, Azure, GCP and more). Open source CLI. No DB required."

# it is necessary to specify the name_template of the snapshot, or else the snapshot gets created with
# two dash(-) which results in a 500 error while downloading
snapshot:
  name_template: "{{ incpatch .Version }}-next"

checksum:
  name_template: "checksums.txt"

release:
  # Visit your project's GitHub Releases page to publish this release.
  draft: true
  extra_files:
    - glob: ../dashboard_ui_assets.tar.gz

changelog:
  skip: true

brews:
  - ids:
      - homebrew
    name: powerpipe@{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    tap:
      owner: turbot
      name: homebrew-tap
      branch: bump-brew
    folder: Formula
    url_template: "https://github.com/turbot/powerpipe/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://powerpipe.io/"
    description: "powerpipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
    skip_upload: auto
    install: |-
      bin.install "powerpipe"
