builds:
  - id: powerpipe-linux-arm64
    binary: powerpipe
    goos:
      - linux
    goarch:
      - arm64

    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++

    # Custom ldflags.
    #
    # Default: '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser'
    # Templates: allowed
    ldflags:
      # Go Releaser analyzes your Git repository and identifies the most recent Git tag (typically the highest version number) as the version for your release.
      # This is how it determines the value of {{.Version}}.
      - -s -w -X  main.version={{.Version}} -X main.date={{.Date}} -X main.commit={{.Commit}} -X main.builtBy=goreleaser

  - id: powerpipe-linux-amd64
    binary: powerpipe
    goos:
      - linux
    goarch:
      - amd64

    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++

    ldflags:
      - -s -w -X  main.version={{.Version}} -X main.date={{.Date}} -X main.commit={{.Commit}} -X main.builtBy=goreleaser

  - id: powerpipe-darwin-arm64
    binary: powerpipe
    goos:
      - darwin
    goarch:
      - arm64

    env:
      - CC=oa64-clang
      - CXX=oa64-clang++

    ldflags:
      - -s -w -X  main.version={{.Version}} -X main.date={{.Date}} -X main.commit={{.Commit}} -X main.builtBy=goreleaser

  - id: powerpipe-darwin-amd64
    binary: powerpipe
    goos:
      - darwin
    goarch:
      - amd64

    env:
      - CC=o64-clang
      - CXX=o64-clang++

    ldflags:
      - -s -w -X  main.version={{.Version}} -X main.date={{.Date}} -X main.commit={{.Commit}} -X main.builtBy=goreleaser

archives:
  - format: tar.gz
    id: homebrew
    name_template: "{{ .ProjectName }}.{{ .Os }}.{{ .Arch }}"
    files:
      - none*

# it is necessary to specify the name_template of the snapshot, or else the snapshot gets created with
# two dash(-) which results in a 500 error while downloading
snapshot:
  name_template: "{{ incpatch .Version }}-next"

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true

release:
  prerelease: auto

brews:
  - ids:
      - homebrew
    name: powerpipe@{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    repository:
      owner: turbot
      name: homebrew-tap
      branch: powerpipe-brew
    folder: Formula
    url_template: "https://github.com/turbot/powerpipe/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://powerpipe.io/"
    description: "Dashboards for DevOps. Visualize cloud configurations. Assess security posture against a massive library of benchmarks. Build custom dashboards with code."
    skip_upload: auto
    install: |-
      bin.install "powerpipe"
