// Code generated by "stringer -type=BackendType"; DO NOT EDIT.

package backend

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownClientBackend-0]
	_ = x[PostgresDBClientBackend-1]
	_ = x[MySQLDBClientBackend-2]
	_ = x[SqliteDBClientBackend-3]
	_ = x[DuckDBClientBackend-4]
}

const _BackendType_name = "UnknownClientBackendPostgresDBClientBackendMySQLDBClientBackendSqliteDBClientBackendDuckDBClientBackend"

var _BackendType_index = [...]uint8{0, 20, 43, 63, 84, 103}

func (i BackendType) String() string {
	if i < 0 || i >= BackendType(len(_BackendType_index)-1) {
		return "BackendType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BackendType_name[_BackendType_index[i]:_BackendType_index[i+1]]
}
