// Code generated by "stringer -type=DBClientBackendType"; DO NOT EDIT.

package backend

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownClientBackend-0]
	_ = x[PostgresDBClientBackend-1]
	_ = x[MySQLDBClientBackend-2]
	_ = x[SqliteDBClientBackend-3]
	_ = x[DuckDBClientBackend-4]
}

const _DBClientBackendType_name = "UnknownClientBackendPostgresDBClientBackendMySQLDBClientBackendSqliteDBClientBackendDuckDBClientBackend"

var _DBClientBackendType_index = [...]uint8{0, 20, 43, 63, 84, 103}

func (i DBClientBackendType) String() string {
	if i < 0 || i >= DBClientBackendType(len(_DBClientBackendType_index)-1) {
		return "DBClientBackendType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DBClientBackendType_name[_DBClientBackendType_index[i]:_DBClientBackendType_index[i+1]]
}
